spring:
  # spring mvc
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  # freemarker
  freemarker:
    cache: false
    request-context-attribute: request
    template-loader-path: classpath:/templates
    prefix:
    suffix: .html
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/luck
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
# mybatis配置
mybatis:
  mapper-locations: classpath*:sqlmap/*Mapper.xml
  type-aliases-package: com.luck.pojo
